### PR TITLE
Add filename formatting argument

### PR DESCRIPTION
**Pull request by Michoko92**
Make the filenames format configurable with a "--filename_format" argument.

All parameters vary depending on our needs and experiments. Some people play a lot with steps, others with CFG, or image dimensions. And it is very handy to have this information in the filenames. Personally, I have to manually change webui.py every time I update the repo, to fit my needs. The best way to make everyone happy is to make the filenames format configurable with a "--name_format" argument. Using tags is the most flexible and scalable way. Something like:

`--filename_format [STEPS]_[CFG]_[SEED]_[PROMPT]`

The supported tags in the name format are: [STEPS], [CFG], [PROMPT], [PROMPT_SPACES], [WIDTH], [HEIGHT], [SAMPLER], [VARIANT_AMOUNT] and [SEED]. If no format is provided as an argument, it will use the current naming format.

[PROMPT_SPACES] is the same thing as [PROMPT], except that spaces are not replaced by underscores, making copying and pasting prompts from filenames easier.

_(special thanks to Samson for the help with my first PR)_

### CODE REVIEW

**Comment by Michoko92** [comment]
Perfect, thank you!

**Review by codedealer — APPROVED** [review]

**Comment by unnamedplugins** [comment]
The update made in commit c35b37f broke the code - the access to `opt.name_format` was not updated, only the string parameter.  Lines 970 and 974 both need updating to address this mismatch.

**Comment by codedealer** [comment]
@unnamedplugins good catch!

**Comment by Michoko92** [comment]
Thank you @unnamedplugins and @codedealer

**Pull request merged**
