### PR TITLE
Lightwight memory usage

### PR DESCRIPTION
**Pull request by osi1880vr**
# Description

not my work, just pushing it here.
It showed much less VRam usage, its more quick rendering, also it allowes for large number of images per batch on my 3060 it went from 2 to 35 inside the 12GB

Please include:
* relevant motivation
* a summary of the change
* which issue is fixed.
* any additional dependencies that are required for this change.

Closes: # (issue)

# Checklist:

- [x ] I have changed the base branch to `dev`
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by ZeroCool940711 — APPROVED** [review]
LGTM

**Review by hlky — APPROVED** [review]

**Comment by osi1880vr** [comment]
something is wrong here when I check the code... I will pull this and see what I did wrong before I mess up things with this.

**Review by codedealer — COMMENTED** [review]
This basically turns on optimization for everyone overwriting the changes merged in #974 (literally 12 hours ago). I thought we merged that one to address bugs people were having with the previous version of attention.py.

As it stands this PR slashes performance in normal mode (40% for me) to provide better batching but still not on level of just using `--optimized`. I see an increase of memory efficiency but I'd argue that the normal mode was never about memory efficiency but instead about speed. Here's a quick test for 10 images/euler/20 steps and then additional 20 images (only on PR because the current dev OOM's on it)

|                | Dev                                            | Pull Request                                   |
|----------------|------------------------------------------------|------------------------------------------------|
| Batch_size 10  | (6.67s per image) Peak memory usage: 10326 MiB | (10.02s per image) Peak memory usage: 8001 MiB |
| Batch_count 10 | (8.4s per image) Peak memory usage: 7342 MiB   | (12.23s per image) Peak memory usage: 5236 MiB |
| Batch_count 20 | (8.55s per image) Peak memory usage: 7314 MiB  |                                                |
| Batch_size 20  |                                                | (9.89s per image) Peak memory usage: 10808 MiB |

There is an inherent benefit in increasing `batch_size` because it reduces the inference time per image but even `batch_size 20` doesn't get to `batch_count 20` inference times in normal mode.
This PR should theoretically allow larger batch sizes in `--optimized` mode but previous tests showed that after 50 the benefit to speed becomes negligible (`batch_size 50` has about the same time per image as `batch_size 100`)

@hlky @ZeroCool940711 do we really want to go this way?

**Comment by codedealer** [comment]
Lol this was closed as I was writing my essay, oh well

**Comment by osi1880vr** [comment]
Im still very confused 😊

 

I was thinking I do something which was a change tot he system and it brings a benefit. But then it looked like Oh no I just pushed the original code over the alread optimized code.

But now you tell you measured some less memory usage. This ist very confusing now again ☹

 

Maybe I have to try again in a more time environment not rushiong things…

 

 

 

 

Von: Thomas Mello ***@***.***> 
Gesendet: Mittwoch, 14. September 2022 11:29
An: sd-webui/stable-diffusion-webui ***@***.***>
Cc: osi1880vr ***@***.***>; State change ***@***.***>
Betreff: Re: [sd-webui/stable-diffusion-webui] Lightwight memory usage (PR #1108)

 

Lol this was closed as I was writing my essay, oh well

**Pull request closed without merging**
