### PR TITLE
Initial overhaul of documentation

### PR DESCRIPTION
**Pull request by JoshuaKimsey**
Added documents for Streamlit and Gradio.
Added new screenshots for each respective version of the UI. Changed `upscalers` to `image enhancers`.

Documents currently finished:
- linux-installation.md
- image-enhancers.md
- ReadMe

Documents currently still WIP:
- streamlit-interface.md
- gradio-interface.md

Documents still awaiting changes:
- windows-installation.md (I'll need help for this one)
- custom-models.md
- cli.md

Feedback is welcomed and needed on any changes that should happen for the documents already finished.

(Also fixed small bug with the `webui_streamlit.yaml` file)

# Checklist:

- [x] I have changed the base branch to `dev`
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by lggomez** [comment]
Any working examples of the cli mode? I'm just getting into the project and was planning to add support for the full-ema model, for which it seems more convenient to add to the cli parameters

I'm willing add some more examples and work on that section if that seems fine

**Comment by JoshuaKimsey** [comment]
@lggomez Yeah, I know there is one, but I have not messed around with it. I think it's mostly based on the Gradio version, but I could be wrong about that.

**Comment by JoshuaKimsey** [comment]
This is far enough along now that I am making it into a full PR. Somethings still need some improvement, but overall I think it's ready to be merged. We can keep working out details as we move along and add more features.

**Review by codedealer — CHANGES_REQUESTED** [review]
Constantly renaming files does no one any good 👀

**Comment by JoshuaKimsey** [comment]
Ok, now everything should be good to go, hopefully.

**Review by codedealer — APPROVED** [review]

**Pull request merged**
