### PR TITLE
Fix strange stepping error in ddim and plms

### PR DESCRIPTION
**Pull request by osi1880vr**
This is a quick and dirty to fix to the issue with sampling steps for DDIM and PLMS.
Both samplers use the same code to generate steps_out.
This will lead to an error if the array contains a numer 1000.
By changing the line creating the numer 1000 I work around the issue, which in the first place I do not understand any further then how to work around it like this.
The workaround has a side effect which will user 10 sample steps instead of 9 since 9 creates the error, or it uses 112 steps instead of 107 as again 107 would create the error like 111 too.
I found this as a possible fix at this link, so it is not my original work or idea :)
https://pullanswer.com/questions/indexerror-index-1000-is-out-of-bounds-for-dimension-0-with-size-1000

### CODE REVIEW

**Comment by codedealer** [comment]
@osi1880vr thanks for bringing this up!

PRs are opened against `dev`. Please tidy it up before we can merge.

**Comment by osi1880vr** [comment]
Hello Thomas,

 

Im terrible stupid with this things 😉

I will try my best, what you mean by tidy it up?

 

Thanks a lot

Cheers

Werner

 

Von: Thomas Mello ***@***.***> 
Gesendet: Sonntag, 11. September 2022 12:59
An: sd-webui/stable-diffusion-webui ***@***.***>
Cc: osi1880vr ***@***.***>; Mention ***@***.***>
Betreff: Re: [sd-webui/stable-diffusion-webui] Fix strange stepping error in ddim and plms (PR #1009)

 

@osi1880vr <https://github.com/osi1880vr>  thanks for bringing this up!

PRs are opened against dev. Please tidy it up before we can merge.

**Comment by codedealer** [comment]
@oc013 I changed the base branch of your PR and now it has history from `master` along with your changes. If you don't want to bother with rebasing/solving conflicts you can just close this PR and open a new one forked from `dev` branch instead of `master` and opened against `dev` branch with your changes.

**Comment by osi1880vr** [comment]
Oh I see, makes sense. I will redo it from dev and not do the merging hussle 😉

 

You see my new PR very soon.

 

Thank you mate for the hints

 

 

 

 

Von: Thomas Mello ***@***.***> 
Gesendet: Sonntag, 11. September 2022 13:42
An: sd-webui/stable-diffusion-webui ***@***.***>
Cc: osi1880vr ***@***.***>; Mention ***@***.***>
Betreff: Re: [sd-webui/stable-diffusion-webui] Fix strange stepping error in ddim and plms (PR #1009)

 

@oc013 <https://github.com/oc013>  I changed the base branch of your PR and now it has history from master along with your changes. If you don't want to bother with rebasing/solving conflicts you can just close this PR and open a new one forked from dev branch instead of master and opened against dev branch with your changes.

**Pull request closed without merging**
