### PR TITLE
Animation generating with ~ tilde prompt in txt2img

### PR DESCRIPTION
**Pull request by machineinthegod**
Implemented support for creating animation between two prompts using tilde ~ in txt2img.
Most animation logic is in animate.py, there's important addition to KDiffusionSampler class (animation only works with those). Rest of the changes are additional tab for viewing the video in txt2img in gradio, and small changes in process_images and txt2img to pass the parameters.

(It's not naïve animation generation, like img2img loopback methods, there's logic to try and get as smooth animation as possible instead of jumpy animation with noise and things randomly popping in and out of existence between frames)

Requires getting openh264 codec in windows to encode the mp4 video (but the frames are generated either way).

### CODE REVIEW

**Comment by codedealer** [comment]
Hello @machineinthegod thanks for your contribution!

New PRs are opened against `dev` branch.

**Comment by dudumaroja** [comment]
how this whould work? exaplem of a prompt please

**Comment by hlky** [comment]
> Hello @machineinthegod thanks for your contribution!
> 
> New PRs are opened against `dev` branch.

Conflicts changing it to dev, leaving it for now.

@machineinthegod 
(reproducible) examples would be helpful

**Comment by pancoaster** [comment]
This works well, but I suggest a few things before merge.  first, the process images fails at times.  the animation process should save off each image as it is generated, rather than store then all into ram.  thoughts on getting this feature merged so I can start to implement more changes?

**Pull request closed without merging**
