### PR TITLE
Add NSFW filter to avoid unexpected

### PR DESCRIPTION
**Pull request by GRMrGecko**
When working with stable diffusion, I've came across some unexpected NSFW content which I do not wish to accidentally come across when showing friends how cool stable diffusion is. I understand some people may be after NSFW content, so I added an option to disable the filter.

I considered adding to webui_streamlit, however streamlit shows you the diffusion steps, so its kind of too late there if the content is unexpectedly NSFW.

### CODE REVIEW

**Review by hlky — CHANGES_REQUESTED** [review]
This is a great feature, there are many circumstances when it would be highly inappropriate for an accidental nsfw result to be displayed.

However, Rick Astley's image is subject to copyright, so we can't include that, make it either a plain black image file or preferably just make a plain black image in the code.

Also, the default option should be nsfw off, anyone who wants it enabled can set their own UI defaults in the config file.

**Comment by codedealer** [comment]
I would like to add that the model for nsfw filtration should be lazy loaded only when the option is turned on. One of the main reason many forks got rid of it is because it wastes memory sitting there.

**Comment by GRMrGecko** [comment]
I decided to go with a black image to allow people to replace it if they find themselves wanting a funny image when NSFW content is found. I have implemented lazy loading and disabled by default per your request.

**Review by hlky — APPROVED** [review]

**Review by codedealer — CHANGES_REQUESTED** [review]
feature PRs against `dev` branch

**Comment by GRMrGecko** [comment]
@codedealer re-based on dev branch.

**Review by codedealer — APPROVED** [review]

**Pull request merged**
