### PR TITLE
webui: display the GPU in use during startup

### PR DESCRIPTION
**Pull request by mchaker**
tell the user which GPU the code is actually going to use before spending lots of time loading everything onto the GPU

also fix a typo

### CODE REVIEW

**Comment by mchaker** [comment]
Wait, I found a bug. Pytorch respects CUDA_VISIBLE_DEVICES, so looking for any index other than 0 will fail on startup. Hold on. Will comment here again when fixed.

**Comment by mchaker** [comment]
Bug fixed. Ready for review

**Review by hlky — APPROVED** [review]

**Review by codedealer — APPROVED** [review]

**Review by ZeroCool940711 — APPROVED** [review]

**Comment by codedealer** [comment]
@mchaker 
It's not related to this PR but to the previous one you made 9717532b3b0e09914fdde85221d3edb99d792119. Is there a way to not rely on a try/catch block when looking for a scoped down GPU? I imagine the majority of people will now see a warning in a console output that provides on useful info and will only bring anxiety.

**Comment by mchaker** [comment]
@codedealer, good point. I could gate the warning behind a SD_WEBUI_DEBUG=1 env var?

**Comment by codedealer** [comment]
@mchaker guess that could be an option for now. Push it here so we can merge all the stuff related to GPU info at once.

**Review by codedealer — APPROVED** [review]
Should suffice for now

**Pull request merged**
