### PR TITLE
Allow for configurable filename format

### PR DESCRIPTION
**Pull request by Michoko92**
Make the filenames format configurable with a "--name_format" argument.

All parameters vary depending on our needs and experiments. Some people play a lot with steps, others with CFG, or image dimensions. And it is very handy to have this information in the filenames. Personally, I have to manually change webui.py every time I update the repo, to fit my needs. The best way to make everyone happy is to make the filenames format configurable with a "--name_format" argument. Using tags is the most flexible and scalable way. Something like:

`--name_format [STEPS]_[CFG]_[SEED]_[PROMPT]`

The supported tags in the name format are: [STEPS], [CFG], [PROMPT], [PROMPT_SPACES], [WIDTH], [HEIGHT], [SAMPLER], [VARIANT_AMOUNT] and [SEED]. If no format is provided as an argument, it will use the current naming format.

[PROMPT_SPACES] is the same thing as [PROMPT], except that spaces are not replaced by underscores, making copying and pasting prompts from filenames easier.

_(special thanks to Samson for the help with my first PR)_

### CODE REVIEW

**Comment by codedealer** [comment]
@Michoko92 hello. Thanks for contributing! 

Please don't make pull requests against the `master` branch. Please edit the base branch or create a new PR against `dev` with clean commit history.

**Comment by Michoko92** [comment]
I'm sorry, I'm still very new to GitHub. Not sure how to do that, but I'll see if I can figure it out.

**Comment by codedealer** [comment]
@Michoko92 simply changing the branch will introduce conflicts because out branches aren't synchronous with each other. The most newcomer friendly way of going about this would be to close this PR, pull new changes from `dev` to your local copy, make your changes and opening a new PR against `dev` branch.

This way you won't have to deal with merge conflicts and messed commit history.

**Comment by Michoko92** [comment]
OK, by seeing the result, that's what I suspected. I'll try this, thanks.

**Pull request closed without merging**
