### PR TITLE
Update, Refactor, and Split Gradio UI

### PR DESCRIPTION
**Pull request by john-warnes**
# Refactor and split Gradio frontend.py 

## Why

The goal is to split the large file into logical chunks, and make it easier for me and others to work on parts independently.
I then can work of cleaning up and updating the Gradio UI. I've formatted, tried to unify the code styles, and added comment where I think they can be useful.

I've tried to tested all features and they should be working.

## New Features

set to 512x512 images as request in discussions: [542](https://github.com/sd-webui/stable-diffusion-webui/discussions/542), [569](https://github.com/sd-webui/stable-diffusion-webui/discussions/569)

### Larger 512x512 txt2img output
image

### Larger 512x512 txt2txt input
image

### The generate button being huge.
Bad: 
 image
Fix:
 image

### Hide the dead seed box near the generation parameters. (Copy button still works)
Bad:
 image
Fix:
 image

## Changes
- refactored frontend.py, split into new files.
- new files: ui_image_to_image.py, ui_text_to_image.py, ui_image_lab.py.
- refactored, and formatted styles.css, custom.css.
- Bug fix 3.3.1: Make the generate button not fill 1/2 the screen width
- Bug fix 3.3.1: Hide the dead seed box.

## CheckList
- [x] I have changed the base branch to `dev`
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (None needed)

### CODE REVIEW

**Review by codedealer — CHANGES_REQUESTED** [review]
@john-warnes hello, thank you for your contribution!

I really appreciate the effort to refactor the frontend code, however I'm a bit confused about some of the changes in this PR. It seems to fix things that aren't really broken?

My suspicion is you're using modified environment to run Web UI? The current Gradio version is 3.1.6, have you updated yours without reflecting this change in this PR?

**Comment by john-warnes** [comment]
Strange, I used the docker to build and run thinking that would update the env to be the correct versions.
Inside my docker the conda says gradio is a 3.3.1
image

I was  not planing to do any dependency updates, but maybe I did a long time ago and it's being carried into the docker somehow? I am on Linux if that make a difference.

Maybe I should just update the Gradio version?

I'll do a full repo clean and test it.

**Comment by john-warnes** [comment]
Ahh there is a Gradio version inconsistency.
In `environment.yaml` is will install `gradio==3.1.6`
And if you build and run the webui on native hardware it seems you get that that version.

But if build the docker it also installs `ui_requirements.txt` containing `gradio==3.3.1` and that is the version you get.

**Comment by john-warnes** [comment]
I've fixed this so that it now works correctly with Gradio 3.1.6 when run on raw hardware, as well as Gradio 3.3.1 when running inside docker.

**Review by codedealer — CHANGES_REQUESTED** [review]
It's good that it compiles now!

There is a little layout issue regarding txt2img tab. We have the center column (the one with the Image component) larger than the other two (the previous hack put it at 250%). This breaks in newer versions of Gradio and seems to break in this PR as well.

Also want to give you a heads up, by the looks of it we will be merging #1179 first and it also changes frontend.py. Would be awesome if those changes were also incorporated into the refactor effort, thanks and apologies for the upcoming conflicts.

**Comment by hlky** [comment]
This isn't needed. There are no issues with the current frontend.py

**Comment by john-warnes** [comment]
Of course I would be willing to make sure my changes didn't break any existing pull request like #1179.

But I known refactors can be controversial, so if you don't think there is any benefit to it, I understand.

**Pull request closed without merging**
