### PR TITLE
Using the Optimization from Dogettx 

### PR DESCRIPTION
**Pull request by TingTingin**
This attempts to address  https://github.com/sd-webui/stable-diffusion-webui/issues/957 These changes are from Doggettx from here https://github.com/CompVis/stable-diffusion/compare/main...Doggettx:stable-diffusion:main I noticed no performance differences with the current attention.py on normal optimized turbo or optimized mode I also noticed no differences with this change either but maybe this will address https://github.com/sd-webui/stable-diffusion-webui/issues/957 this is mostly here so that people can test

### CODE REVIEW

**Comment by codedealer** [comment]
Some people actually noticed performance improvements on streamlit version but couldn’t confirm if it’s related to changes in attention.py
Maybe we should put it in another branch for everyone to test.

**Comment by mchaker** [comment]
I have done some performance comparisons for the Doggettx optimizations here:

https://github.com/sd-webui/stable-diffusion-webui/issues/673#issuecomment-1241075800

**Comment by mchaker** [comment]
optimizedSD (basujindal) vs Doggettx, yes

**Comment by joanroig** [comment]
With this pull request and an RTX 2060 6GB I can render square images in maximum resolution of:
- 1080p in optimized mode (2:37 minutes) 
- 832p in normal mode (0:59 minutes)
Impressive results 👏

**Comment by codedealer** [comment]
So did it address #957?

**Comment by joanroig** [comment]
> So did it address #957?

For me yes, in non-optimized it kept around 3.73it/s - 4.03it/s for a 512p image, which is the same as the original version.

**Comment by joanroig** [comment]
> So did it address #957?

In non-optimized it took around 1 second more for a 512p image compared to the original version, so it's slightly worse in my experience but it enables having higher resolutions with the same vram.

**Comment by JigenD** [comment]
This seems to address https://github.com/sd-webui/stable-diffusion-webui/issues/1083

**Review by hlky — APPROVED** [review]

**Review by codedealer — APPROVED** [review]

**Comment by codedealer** [comment]
Well then

**Pull request merged**
