### PR TITLE
Re-merge #611 - View/Cancel in-progress diffusions

### PR DESCRIPTION
**Pull request by cobryan05**
[PR #611 ](https://github.com/sd-webui/stable-diffusion-webui/pull/611) got pretty messed up in the transition to 'dev'. This commit re-merges the feature branch.

### CODE REVIEW

**Comment by cobryan05** [comment]
Hey @codedealer , while you're on a role closing PRs any chance this one can get a little attention? It's been lonely and I just rebased it

**Comment by codedealer** [comment]
@cobryan05 I see commits coming in still. Is it ready for review?

**Comment by cobryan05** [comment]
Yeah it's ready for review. I'll stop pushing commits, I was just keeping it up to date with my local changes while it was waiting.

**Review by codedealer — APPROVED** [review]
LGTM

**Pull request merged**
