### PR TITLE
JobManager: View and skip active iteration

### PR DESCRIPTION
**Pull request by cobryan05**
Adds buttons to the JobManager dialog to view the actively iterating image batch, or to skip the actively generating image batch and continue with the rest of the batches

### CODE REVIEW

**Comment by cobryan05** [comment]
Added a grid output of steps, per https://github.com/hlky/stable-diffusion/discussions/238 .
There must be some 'finalize' step on the images that are not currently being run on the intermediate images, so it's not giving you the exact output you'd get if that was your final step size. 

image

**Comment by Hafiidz** [comment]
Hi, I am still new to this, just curious on the adding grid of history/batch step, does the new changes added VRAM requirement ya, or it will simply saved to file directly after each step? thanks for the great work

**Comment by cobryan05** [comment]
It shouldn't increase VRAM at all. Every preview it generates does cause a
slight slow down. By default it doesn't generate anything, so no hit at
all. The history grids must be enabled under the "Batch Progress Settings"
where you can also pick how often it makes a preview

**Comment by cobryan05** [comment]
There was no missing post-processing step, I was just using the wrong image that it passed back
image

**Comment by OWKenobi** [comment]
Hi,

I am amazed at your speed on which you picked up my request! I tried it out by copying the 2 files jobmanager and webui in my latest copy of stable-diffusion-main,

it worked up to the point when I activated "enable batch progress grid" - only then it crashed with this error:

      Input type (torch.cuda.HalfTensor) and weight type (torch.HalfTensor) should be the same

I think some autocast must be missing in your code. So sad, wanted to try it today ;-)

**Comment by cobryan05** [comment]
> ```
>   Input type (torch.cuda.HalfTensor) and weight type (torch.HalfTensor) should be the same
> ```

Is there more to that error message? What command line parameters are you using (any of the 'optimized' fixes?)

**Comment by cobryan05** [comment]
Seems to be caused by running with --optimized.  I think the error message is basically saying "The input image is on the GPU. The model is on the CPU. They must be on the same device"

I got it to work with the --optimized tags, but it is *not* fast.  From ~0.2s per image preview without --optimized to ~8s per image preview with --optimized. You'll probably want to set your generation interval a bit higher if running this optimized.

**Comment by OWKenobi** [comment]
Hello cobryan,

I can confirm that it crashed using --optimized or --optimized-turbo, and applying your patch, it doesn't crash anymore. So good news so far!

However, there must be something fundamentally wrong with the logic of the patch; for example: creating a 2 steps image 512*512 optimized takes 3,5s on my pc, as measured by the gui, this means roughly 1,8 seconds per iteration, including overhead (indeed, the backend measures 1.01 it/s)

How on earth can the creation of a single - 1 step - small-res- preview take 6 seconds, when the full-blown process from start to end for 2 steps needs 3,5seconds in total?

Also, I thought that the whole resolution images would be saved into the gallery, so that I go straight from them to the upscaler, or right-click save, just as if I had run a batch job. I could care a bit less if it takes 6 seconds per image, if I at least got the full resolution out.

Maybe you can copy-paste the code that actually renders the FINAL image in full res and use it for the intermediate steps, as this seems to be way faster!?

my (very innocent logic) seems to indicate, that, instead of 

     if opt.optimized:
                step_preview_model = copy.deepcopy(modelFS).to("cpu")

you maybe have to use 

   if opt.optimized:
                modelFS.to(device)

Like further down in the code. This seems to indicate, that in optimized mode, you still need to copy the model to the gpu, and then use 
            x_samples_ddim = (model if not opt.optimized else modelFS).decode_first_stage(samples_ddim)
on the gpu to actually get the x_sample, and from there
                image = Image.fromarray(x_sample)

for me this is all gibberish, but maybe you get my idea.

thanks for your work, I appreciate it a lot!

**Comment by cobryan05** [comment]
> How on earth can the creation of a single - 1 step - small-res- preview take 6 seconds, when the full-blown process from start to end for 2 steps needs 3,5seconds in total?

optimized mode splits what parts of the model are on the CPU and the GPU. During generation, the "create an image" model is on the CPU, while the 'diffuse the image' model is on the GPU.  The whole point of optimized mode is that they are not both in VRAM at the same time, but now that you want to generate images in the middle of diffusion you need both models.

So right now it generates the image on the CPU.  Chances are we could do it on the GPU, since we aren't actually in the middle of a forward pass, so there might be room on the GPU, but I don't know. There definitely is on my 11GB card, but that's not what optimized mode is targeting.

There's some work I want to do that may incidentally address the issue, but no promises on anything.

**Comment by OWKenobi** [comment]
Halleluyah!!!! I just right now feel like an AI! Without knowing at all what this code is actually doing, but having seen similar code before, I was able to diffuse a solution:

   # If in optimized mode then make a CPU-copy of the model to generate preview images
   if opt.optimized:
        modelFS.to(device)
        step_preview_model = modelFS

this fixes it for optimized mode! **Can confirm rendering 512x512 with 1.2i/s and peak memory usage of 4.2GB!!**

**Comment by OWKenobi** [comment]
Just to make sure, I tested both --optimized and --optimized-turbo. Both work on my 6GB card with the same memory footprint as before the patch. Since the command "modelFS.to(device)" happens anyways a few lines later, I think this is actually intended behavior.

For people with sluggish UI, I would recommend a symmetrical option to the grid option: 
 [  ] Save Progress Images To Gallery     [X] Save Progress Images To File

So if I am going to create 100 images, I can just open up my file manager and watch the progress there - I like this workflow anyways, since all the images have correct filenames, are jpg instead of base png and I can quick-delete the ones I don't need and preview with onboard linux tools.

**Comment by d3nzil** [comment]
Hello, this looks very helpful, thanks for making it. 
I was wondering if it would be possible to expand this to save full images instead of only grid? Could be nice for making "image growth" videos as well as getting the right variant from more dynamic samplers like euler_a. 
I'm trying to figure out the code myself, but it will probably take me forever to even understand the basics...

**Comment by OWKenobi** [comment]
Hi d3nzil,

yes it's possible. To display them in the grid is only one more line of code, it almost looks like an animation when you scroll down through all of them!
Also saving the images automatically is possible, but it means copy-pasting a lot more code from further down below, where the final images are stored, so my approach is too quick and dirty to share it :D 

One last thing. Just after I managed to do all this, I realized, what I didn't know about Stable Diffusion before: the image on step 7 of 8 steps is NOT the same as the image at step 7 of 7 steps. I used to think that the images base on each other, in reality, "steps" only says - "you have to achieve the result in x steps" - and each step count produces a completely different pack of images. Its still a very impressive animation, just not a shortcut for my work ^^

**Comment by d3nzil** [comment]
Hi OWKenobi,

> One last thing. Just after I managed to do all this, I realized, what I didn't know about Stable Diffusion before: the image on step 7 of 8 steps is NOT the same as the image at step 7 of 7 steps. I used to think that the images base on each other, in reality, "steps" only says - "you have to achieve the result in x steps" - and each step count produces a completely different pack of images. Its still a very impressive animation, just not a shortcut for my work ^^

I admit that I also expected that the output would be independent. But it explains why I was seeing very different images from the preview compared to the final result with different step number.

For now I managed to use txt2img from webui.py in a script that repeatedly runs Stable Diffusion and generates the final images for different step numbers. Works well enough for now and the result video was fun to watch.

But the time to do this adds so quickly that I'll probably try looking into why the step number affects the "in progress" image so much. Maybe some configuration could fix that... but first I should clean up the script of mine, so I can share it with anyone wanting to do the same.

**Comment by d3nzil** [comment]
Just one quick update, I tried to cleanup the script of mine and dumped it here: https://github.com/d3nzil/stable-diffusion-webui

**Comment by Kallamamran** [comment]
I get no batch process images/grid no matter what setting I use
image

**Comment by OWKenobi** [comment]
Hi Kallamamran,

this is because it never was implemented. I did it on my local machine only. I remember it was only one line of code in webui.py, a line like

            output_images.append( intermediary-image )

but I forgot where exactly this was located. and you have to find the variable name of that intermediate image. A maintainer of this repo probably could point you more exactly. Now I think my version got overwritten, and I stopped caring, since the results were not the same as lowering step size, so I'm actually not using the feature anymore (it is still interesting though)

**Pull request merged**
