### PR TITLE
Streamlit txt2img page settings now follow defaults

### PR DESCRIPTION
**Pull request by Dekker3D**
# Description
Some options on the Streamlit txt2img page now follow the defaults from the relevant config files.

Please include:
* Motivation: I was getting sick of having to disable writing metadata prompts and sorting by prompt every time I start this :D

* Summary: Some txt2img page settings were set to True or False instead of reading their defaults from the streamlit config files. I fixed this, as far as I could find these issues. img2img and txt2vid did not have this issue.
* Fixed issues: none. I did not file any.
* Additional dependencies: none.

Closes: None

# Checklist:

- [x] I have changed the base branch to `dev`
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by Dekker3D** [comment]
I may be a dumbass. While this is a super simple change, apparently I forgot to test and I broke something.

**Comment by Dekker3D** [comment]
Aaand now it works.

**Comment by hlky** [comment]
I tested this and got the error related to `st.session_state["defaults"]`

Apparently setting the defaults in `webui_streamlit.py` was causing issues with defaults being overwritten on generation/refresh, this doesn't appear to be happening now, and the defaults update when the page is refreshed after `webui_streamlit.yaml` is updated.

@ZeroCool940711 had been dealing with the `st.session_state["defaults"]` errors so I will leave this for him to confirm the exact issue, and test whether this is working properly.

**Comment by Dekker3D** [comment]
@hlky I'm not getting that error. Is it just a thing that only happens to some people, somehow?

**Comment by Dekker3D** [comment]
It seems the error only happens for me when refreshing the page, with or without this PR.

**Comment by hlky** [comment]
> Is it just a thing that only happens to some people, somehow?

It appears to only happen to some people, and only some of the time. It's never truly broken, restarting the script or reloading the page fixes it, but any error can be confusing to people.

**Comment by hlky** [comment]
Testing this again there doesn't appear to be any issue, so I will merge this.

**Pull request merged**
