### PR TITLE
many people asked, so..

### PR DESCRIPTION
**Pull request by neonsecret**
you can leave out the readme change and funding etc

### CODE REVIEW

**Comment by neonsecret** [comment]
> what's the difference between this and doggetx?

mine is a successor of it, as doggettx took my old source code when creating it

**Comment by cobryan05** [comment]
> this is obviously alot more than that at least this PR anyway

He autoformatted the entire repo in the same commit that he also made actual changes to code.  Given the commits and the messages, I think this may be more of a "here, stop bothering me about adding it" than an actual pull request 😆

**Comment by neonsecret** [comment]
> > this is obviously alot more than that at least this PR anyway
> 
> He autoformatted the entire repo in the same commit that he also made actual changes to code. Given the commits and the messages, I think this may be more of a "here, stop bothering me about adding it" than an actual pull request 😆

up to the repo owner whether to merge this or not, as I said, he can only take what he wants from my fork

but his code was a mess so cleaning it is more of a pro then a con

**Comment by swfsql** [comment]
My suggestion for a cleaner PR is to run the formatting (exclusively) in a different branch and then compare `neonsecret`'s branch to it.

I didn't look much into it, but from what I saw, Doggettx's change allows for (1, 2, 4, 8, 16, 32, ...,) inner steps, whichever is faster and still under the free mem limit - and as TintTingin noticed, even manually defined caps lower than that limit are also possible.  
One interesting property is that if you got all the memory you need, you basically won't have any slowdown as it will still run in a single inner step.

**Comment by codefaux** [comment]
For those of us who didn't ask and apparently missed the memo, can someone clarify what this does?

**Comment by mchaker** [comment]
> My suggestion for a cleaner PR is to run the formatting (exclusively) in a different branch and then compare `neonsecret`'s branch to it.
> 
> I didn't look much into it, but from what I saw, Doggettx's change allows for (1, 2, 4, 8, 16, 32, ...,) inner steps, whichever is faster and still under the free mem limit - and as TintTingin noticed, even manually defined caps lower than that limit are also possible. One interesting property is that if you got all the memory you need, you basically won't have any slowdown as it will still run in a single inner step.

Agreed. I performed a speed comparison and found `Doggettx` optimizations faster: https://github.com/sd-webui/stable-diffusion-webui/issues/673#issuecomment-1241075800

The `basujindal`/`neonsecret` optimizations seemed to be better on VRAM at first glance, but at the expense of speed. I have yet to see a 4GB card comparing `Doggettx` and `basujindal`/`neonsecret`

**Comment by mchaker** [comment]
Woah, with the latest cherrypick, are the Doggettx and neonsecret modifications combined?

**Pull request closed without merging**
