### PR TITLE
Amd gpu docker

### PR DESCRIPTION
**Pull request by Seacant**
# Description
AMD support can be built by prefixing your compose commands with 
`docker compose -f docker-compose.yml -f docker-compose.amd.yml ...`

or, by setting 
```
export COMPOSE_FILE=docker-compose.yml:docker-compose.amd.yml
```
in your `.profile` or through a tool like `direnv`

Closes: Discord #installation-packing:AMD, at least for Linux hosts

# Checklist:

- [x] I have changed the base branch to `dev`
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by codedealer — COMMENTED** [review]
Have you checked this fix instead of headless mode? Seems like a better way of handling user prompt on startup.
https://github.com/sd-webui/stable-diffusion-webui/pull/1364#discussion_r984085705

**Comment by Seacant** [comment]
> Have you checked this fix instead of headless mode? Seems like a better way of handling user prompt on startup. [#1364 (comment)](https://github.com/sd-webui/stable-diffusion-webui/pull/1364#discussion_r984085705)

It fixes the current prompt, yeah, but docker (in the intended configuration, which is why I left it modifiable in case they want to `docker run -it` or something) is really, truly, specifically headless and Streamlit should really know that so that they _never_ open STDIN, expecting it to be there.

**Review by codedealer — APPROVED** [review]
Makes sense to me. Merging this in hopes people with AMD setup will check out `dev` and test it.

**Comment by WeaponXII** [comment]
Is this still expected to work only for machines with Linux as the host, not machines running WSL?

**Comment by Seacant** [comment]
> Is this still expected to work only for machines with Linux as the host, not machines running WSL?

As far as I know, yeah. You're free to try it, but my understanding is that AMD GPUs don't expose the correct drivers (or something, I'm not much of a hardware guy) to WSL2 so there's no passthrough.

**Comment by ZaneH** [comment]
Chiming in, I noticed these files got lost in dev, what a shame :smiling_face_with_tear: 

I've had great success using commit fdf600b49ad7bb841e6d4f3243be8495d4d5439f with some minor changes to fix a dependency issue and improve stability. I've created a Draft PR with those changes here: https://github.com/sd-webui/stable-diffusion-webui/pull/1505

When merging it says there are only a few changes, but the project structure is drastically different. Not sure why.

**Pull request merged**
