### PR TITLE
fix no frontend module bug

### PR DESCRIPTION
**Pull request by Molers**
ModuleNotFoundError: No module named 'frontend'

### CODE REVIEW

**Review by codedealer — COMMENTED** [review]
Hello, @Molers!

I don't see why is this needed? Autoloading should take care of that without touching system path. Can you reference the issue this solves?

**Comment by Molers** [comment]
When i run python scripts/webui.py, I have this problem，I think the path is not provided correctly，Maybe I'm the only one with this problem..
image

**Comment by HenkDz** [comment]
I have this issue as well.

**Comment by Hafiidz** [comment]
@HenkDz & @Molers , is it possible to ensure you are up to date with master, ensure you are in `ldm` conda environment and re-run? 

Secondly @Molers , do note that new PR should be sent to `dev` branch first & if it's okay now, best to close this PR.

**Pull request closed without merging**
