### PR TITLE
WIP: Fix optimized mode

### PR DESCRIPTION
**Pull request by marius851000**
This is an unfinished PR that fix the low memory mode (and also update it, allowing the use of the DDIM sampler).

txt2img is limited to DDIM and PLMS sampler.

It now work with 32bit float with 4GiB of VRAM (that is, my GTX1650 Max-Q), at least for 448×448 images.

For now, I only fixed the txt2img version. Will check the img2img, but OptimizedSD work well when used directly with the good option.

I hope I didn’t messed up or failed to see some obvious issue, thought.

### CODE REVIEW

**Comment by marius851000** [comment]
I’ll also add I have barely any idea of what I’m doing. This is mostly trial and error, finding the different with the original optimizedSD scripts.

**Comment by Soul-Burn** [comment]
Unless I'm mistaken, sd-webui already handles all samplers, regardless of optimized mode. From what I can tell, this PR reduces functionality compared to what we have today.

I always run optimized, and could use all samplers successfully.

**Comment by Soul-Burn** [comment]
See my PR https://github.com/sd-webui/stable-diffusion-webui/pull/790

There's an issue with the current implementation where the sampling finishes successfully (see the progress bars reaching 100%) but then runs out of memory when decoding the images. My PR there fixes that. Maybe that's the issue you've seen?

**Comment by marius851000** [comment]
@Soul-Burn Tried it, it doesn’t solve the problem. It seems to be related to the two half of the diffuser models being loaded in cuda during loading, (kinda like the turbo mode being always active whether the option is enabled), instead of each half of the model being loaded once at a time.

**Pull request closed without merging**
